apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: slack-send-message
  namespace: argo
spec:
  workflowMetadata:
  entrypoint: slack-send-message
  templates:
    - name: slack-send-message
      inputs:
        parameters:
          - name: webhook-url
          - name: webhook-token
          - name: message
      http:
        method: "POST"
        url: "{{inputs.parameters.webhook-url}}/{{inputs.parameters.webhook-token}}"
        body: '{"text":"{{inputs.parameters.message}}"}'
