apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: redis-add-key
spec:
  templates:
    - name: redis-add-key
      inputs:
        parameters:
          - name: key
            value: key
          - name: value
            value: value
          - name: host
            value: redisserver.greenops.svc.cluster.local
          - name: port
            value: 6379
      script:
        image: redis
        command: [/bin/sh]
        source: |
          echo 'Adding key "{{inputs.parameters.key}}" to Redis DB at "{{inputs.parameters.host}}:{{inputs.parameters.port}}"'
          redis-cli -h {{inputs.parameters.host}} -p {{inputs.parameters.port}} SET {{inputs.parameters.key}} {{inputs.parameters.value}}
