apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: redis-delete-key
spec:
  templates:
    - name: redis-delete-key
      inputs:
        parameters:
          - name: key
            value: key
          - name: host
            value: redisserver.greenops.svc.cluster.local
          - name: port
            value: 6379
      script:
        image: redis
        command: [ /bin/sh ]
        source: |
          echo 'Deleting a key "{{inputs.parameters.key}}" in Redis DB at "{{inputs.parameters.host}}:{{inputs.parameters.port}}"'
          redis-cli -h {{inputs.parameters.host}} -p {{inputs.parameters.port}} DEL {{inputs.parameters.key}}
