apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: deployment
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: approval
        templateRef:
          name: suspend
          template: suspend
        arguments:
      - name: deploy-application
        templateRef:
          name: argocd-step
          template: argocd-sync-and-wait
        dependencies: [approval]
        arguments:
          parameters:
          - name: argocd-version
            value: "{{workflow.parameters.deploy-application-argocd-version}}"
          - name: application-name
            value: "{{workflow.parameters.deploy-application-application-name}}"
          - name: revision
            value: "{{workflow.parameters.deploy-application-revision}}"
          - name: flags
            value: "{{workflow.parameters.deploy-application-flags}}"
          - name: argocd-server-address
            value: "{{workflow.parameters.deploy-application-argocd-server-address}}"
          - name: argocd-credentials-secret
            value: "{{workflow.parameters.deploy-application-argocd-credentials-secret}}"
